outputs:
  content: '{{ content }}'
  chatCompletion: '{{ chatCompletion }}'
  statusCode: '{{ statusCode }}'
  files: '{{ files }}'

type: workflow
stages:
  - type: retry
    attempts: 3
    backoff: '{{ 2 * attempt }}'
    block:
      outputs:
        content: '{{ response.json()?.message?.content || response.body }}'
        chatCompletion: '{{ response.json() }}'
        statusCode: '{{ response.statusCode }}'
        files: |-
          {{ response.json()
            ? [{ name: 'response.json', data: response.json() }]
            : [] }}
      type: request
      method: POST
      json: >-
        {{ { model: "phi4-mini:3.8b-q4_K_M", messages: [{ role: "user", content: prompt }], stream: false } }}
      timeout: 300
      url: https://james-llm.xc.james-appsec.com/api/chat
      headers:
        Accept: application/json
        Authorization: Bearer {{ apiKey }}
      queryParams: {}
    when: '{{ Array.contains([429, 500, 502, 503, 504], statusCode) }}'
